# This file was generated by GoReleaser. DO NOT EDIT.
class Keygen < Formula
  desc "CSDIP keygen"
  homepage ""
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mklimuk/csdip/releases/download/v0.1.4/keygen_darwin_amd64.tar.gz"
    sha256 "17920b4e82f6c550e8ff0ad5fdc4f046197128ad49f809d6ab023ef47f81bebd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mklimuk/csdip/releases/download/v0.1.4/keygen_linux_amd64.tar.gz"
      sha256 "d3e54fe9a4028ccefbf4df8442a36b363833087bb6c0e00535c72ea667c569a2"
    end
  end

  def install
    bin.install "keygen"
  end
end
